apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: jna9011cs-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jna9011cs-python 
  name: jna9011cs-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: jna9011cs-python
    weight: 100 
